HuggingBento: A Bento-flavoured distro running Hugging Face Transformers
warpstreamlabs/bento pull request #108
Opened 2024-08-24 17:37 UTC by gregfurman

### What is this?

Create distribution of Bento for usage with NLP pipelines. This uses the [knights-analytics/hugot](https://github.com/knights-analytics/hugot) library to allow for running a Hugging Face pipeline with an ONNX model using Go.

It introduces three new components:
- `nlp_classify_text` for text classification pipelines (`processor_text_classifier.go`)
- `nlp_classify_tokens` for token and NER classification pipelines (`processor_token_classifier.go`)
- `nlp_extract_features` for feature extraction pipelines  (`processor_feature_extractor.go`)

Since there is a lot of config overlap between all of these processors,  a single `processor.go` file defines config that is shared amongst all processor types.

All of these will use a shared ONNX Runtime session that is atomically initialised upon creation of one or more HuggingBento processors. This is required to interact with the underlying ONNX Runtime library and can only have a single session created at a time (which required some work when integration testing to ensure runs were not flaky).

## Building HuggingBento
### Docker
Run the below to build a new image on your local (without using any cached layers).
```shell
docker build --platform=linux/amd64  -f resources/huggingbento/Dockerfile -t warpstreamlabs/huggingbento:latest --no-cache .
```
### Binary
- Follow the instructions in the README at [resources/huggingbento/README.md](https://github.com/gregfurman/bento/blob/bd3b7d6828960965257bca9abede1142d08eee5a/resources/huggingbento/README.md) for local installation instructions to get the required external dependencies (C bindings for tokenizer and ONNX Runtime dynamic library).
- Build with `make huggingbento`

## Testing
### Integration Tests
- Running integration tests (on you local) will require the dependencies listed above. There is a test for each of the  

### Steps to manually test
- Once completed, create a Bento config with the following content in `config.yaml`:
```yaml
input:
  generate:
    interval: '@every 10s'
    batch_size: 5
    mapping: root = "Japanese Bento boxes taste amazing!"

pipeline:
  processors:
    - nlp_classify_text:
        pipeline_name: classify-incoming-data
        problem_type: multiLabel
        enable_model_download: true
        model_download_options:
          model_repository: KnightsAnalytics/distilbert-base-uncased-finetuned-sst-2-english

# Out: [{"Label":"NEGATIVE","Score":0.00014481653},{"Label":"POSITIVE","Score":0.99985516}]
# ...
```
- This will load a processor for classifying the sentiment of text using the `KnightsAnalytics/distilbert-base-uncased-finetuned-sst-2-english` model. It will also download the model and relevant files from the huggingface repository.
- The model should download, and once completed, you should get 1-2 batches of identical output:  `[{"Label":"NEGATIVE","Score":0.00014481653},{"Label":"POSITIVE","Score":0.99985516}]`.

### TODO
- Fix GitHub workflow for release
- Write a specififc component guide for usage like with `serverless`
- Implement pipeline for zero shot evaluation
- Perhaps run tests inside `docker-compose` to allow for local testing.

2024-09-08 17:49 UTC, jem-davies commented on website/docs/components/processors/nlp_classify_text.md
I think that there needs to be a way of including these processors somewhere else so that they don't appear on the website. i.e. moved to somewhere like [serverless](https://warpstreamlabs.github.io/bento/docs/guides/serverless/about).

2024-09-16 16:20 UTC, gregfurman commented on website/docs/components/processors/nlp_classify_text.md
> +:::caution BETA
Yeah that makes sense. Will change.

2024-09-16 16:21 UTC, gregfurman commented on resources/huggingbento/install.sh
> +DEPENDENCY_DEST=${DEPENDENCY_DEST:-"/usr/lib"}
The script assumes Linux which where the above would work. Not sure if changing this (by default)

2024-09-16 16:34 UTC, gregfurman commented on website/docs/components/processors/nlp_classify_text.md
What about adding an admonition at the top of the docs saying this is only availble in the `huggingbento` distro? I think trying to generate the docs into a new location is do-able but could end up being more trouble than it's worth if a text-block could suffice. Thoughts?

2024-11-27 17:09 UTC, RJKeevil commented
Please see https://github.com/knights-analytics/hugot/issues/59 for how to remove the ORT dependency for Hugot, would love to see this happen!

2025-07-17 12:41 UTC, gregfurman commented
> Seems that I am getting some errors "Unexpected EOF" - running locally & the CI pipeline, before and after resolving the conflicts with go.mod.

I just updated the example config with the updated syntax. Can you try copy and run the config in the PR description and see what you get?

2025-07-17 12:44 UTC, jem-davies commented
> ```yaml
> pipeline:
>   processors:
>     - nlp_classify_text:
>         name: classify-multi-label
>         path: "./models"
>         multi_label: true
>         enable_download: true
>         download_options:
>           repository: "KnightsAnalytics/distilbert-base-uncased-finetuned-sst-2-english"
> ```

I had done this already yeah - but I just tried again with ☝️  - and it's still: 

```
INFO Running main config from specified file       @service=bento bento_version="" path=./tmp/0717_huggingface/pr.yaml
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=bento
INFO Input type generate is now active             @service=bento label="" path=root.input
INFO Completed download (took 351 ms)              @service=bento label="" path=root.pipeline.processors.0 repository=KnightsAnalytics/distilbert-base-uncased-finetuned-sst-2-english
ERRO Service closing due to: failed to init processor <no label> path root.pipeline.processors.0: unexpected EOF  @service=bento
exit status 1
```

2025-07-18 07:21 UTC, RJKeevil commented
Updating deps is the correct fix here, there was some change in huggingface repositories that required a fix to github.com/gomlx/go-huggingface. Hopefully this should now work!

2025-07-18 10:29 UTC, gregfurman commented
@RJKeevil thanks! I updated to Hugot v0.4.2. I assume this includes the fix?

2025-07-18 11:27 UTC, jem-davies commented
Hey I tried out the latest dependencies and still seeing the issue so I raised an issue here: 

https://github.com/knights-analytics/hugot/issues/79

2025-07-18 12:09 UTC, RJKeevil commented
We will also be making a new small release from hugot this afternoon hopefully, so lets get this issue sorted then perhaps bump to today's release anyway to be on the latest and greatest?

2025-07-18 13:10 UTC, RJKeevil commented
Ok the v0.4.3 release is out!

2025-07-18 14:26 UTC, gregfurman commented
@jem-davies OK all seems to pass fine! Lmk when you get a chance to take another look 🙌 

Thanks @RJKeevil for the quick fix 🙂

2025-07-18 14:29 UTC, jem-davies commented
> @jem-davies OK all seems to pass fine! Lmk when you get a chance to take another look 🙌
> 
> Thanks @RJKeevil for the quick fix 🙂

Yes am taking a good look now 😄

2025-07-18 17:01 UTC, jem-davies requested changes
Looks great! It's great that we can do this with native go now. 

Most of the review comments are mainly nitpicks. 

I just wonder about the inputs and outputs of the processor the way it shapes the data - would it be better if we had some fields that accepted bloblang mappings so rather than relying on the user to use a `branch` processor - they could map it in and out without a `branch` processor? 


Or should we mention the `branch` processor as a part of the documentation for these processors similar to the `http` processor?

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor.go
> +		Beta().
```suggestion
```

I think we should remove this call to Beta() such that it will be marked with `experimental` - which I think makes more sense because the underlying library is in v0?

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor.go
> +			Description("Name of the pipeline. Defaults to a random UUID if not set.").
```suggestion
			Description("Name of the hugot pipeline. Defaults to a random UUID if not set.").
```

Maybe to avoid overloading pipeline with a bento pipeline? NLP pipeline or something - feel free to ignore...

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor.go
> +	onnxFilename string
```suggestion
```

This doesn't seem to be set? - Also then you would want to remove the references in the `hugo.TokenClassificationConfig{}` struct too?

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor.go
> +		if filepath.Ext(modelPath) != "" {
Could get false positives here if you the last directory contains a . in the directory name

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor.go
> +	p.modelPath = modelPath
```suggestion
		if p.modelPath, err = hugot.DownloadModel(modelRepo, modelPath, opts); err != nil {
			return nil, fmt.Errorf("failed to download model %s from HuggingFace to %s: %w", modelRepo, modelPath, err)
		}
		p.log.With("repository", modelRepo).Infof("Completed download (took %d ms)", time.Since(start).Milliseconds())

	}
```

nit: you ca simplify this bit of logic - and also something similar with the pipelineName - using p.pipelineName when assigning to the result of conf.FieldString("name") ?

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor.go
> +type SessionConstructor func() (*hugot.Session, error)
```suggestion
type sessionConstructorKey struct{}

type sessionConstructor func() (*hugot.Session, error)
```

Do these need to be exported?

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_text_classification.go
> +		Field(service.NewBoolField("multi_label").Description("Whether a text classification pipeline should return multiple labels. If false, only the label-pair with the highest score is returned.").Defa
```suggestion
		Fields(
			service.NewStringEnumField("aggregation_function", "SOFTMAX", "SIGMOID").
				Description("The aggregation function to use for the text classification pipeline.").
				Default("SOFTMAX"),
			service.NewBoolField("multi_label").
				Description("Whether a text classification pipeline should return multiple labels. If false, only the label-pair with the highest score is returned.").
				Default(false)).
```

nit: just indentation here is more similar to what we tend to see in other ConfigSpec definitions

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_text_classification.go
> +		OnnxFilename: p.onnxFilename,
```suggestion
```

As above about being unused

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_text_classification.go
> +	p.pipeline = pipeline
```suggestion
	p.pipeline, err = hugot.NewPipeline(p.session, cfg)
	if err != nil {
		return nil, err
	}

```

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_feature_extraction.go
> +		OnnxFilename: p.onnxFilename,
```suggestion
```

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_token_classification.go
> +			Example([]string{"O", "MISC"})).
```suggestion
		Fields(service.NewStringEnumField("aggregation_strategy", "SIMPLE", "NONE").
			Description("The aggregation strategy to use for the token classification pipeline.").
			Default("SIMPLE"),
			service.NewStringListField("ignore_labels").
				Description("Labels to ignore in the token classification pipeline.").
				Default([]string{}).
				Example([]string{"O", "MISC"})).
```

nit just indentation

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_token_classification.go
> +		OnnxFilename: p.onnxFilename,
```suggestion
```

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_zero_shot_classification.go
> +		Field(service.NewStringField("hypothesis_template").Description("Template to turn each label into an NLI-style hypothesis. Must include {} where the label will be inserted.").Default("This example
```suggestion
		Fields(
			service.NewStringListField("labels").
				Description("The set of possible class labels to classify each sequence into.").
				Example([]string{"positive", "negative", "neutral"}),
			service.NewBoolField("multi_label").
				Description("Whether multiple labels can be true. If false, scores sum to 1. If true, each label is scored independently.").
				Default(false),
			service.NewStringField("hypothesis_template").
				Description("Template to turn each label into an NLI-style hypothesis. Must include {} where the label will be inserted.").
				Default("This example is {}."),
		).
```

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_zero_shot_classification.go
> +	}
think you can just do: 

```suggestion
	multiLabel, err = conf.FieldBool("multi_label")
	if err != nil {
		return nil, err
	}
```

if mulit_label has a default of false?

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_zero_shot_classification.go
> +		OnnxFilename: p.onnxFilename,
```suggestion
```

2025-07-18 17:01 UTC, jem-davies commented on website/docs/components/processors/nlp_classify_text.md
irrelevant now the dependency is enabling pure go builds

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor.go
> +		Version("v1.9.0").
```suggestion
		Version("v1.10.0").
```

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_text_classification.go
> +		description
```suggestion
	textClassificationDescription := `### Text Classification
	
Text Classification is the task of assigning a label or class to a given text.
Some use cases are sentiment analysis, natural language inference, and assessing grammatical correctness.
This processor runs text-classification inference against batches of text data, returning labelled classification corresponding to each input.


` + description
```

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_feature_extraction.go
> +		"in tensor/float64 format." + "\n" + description
```suggestion
	featureExtractionDescription := `### Feature Extraction

Feature extraction is the task of extracting features learnt in a model.
This processor runs a feature extraction model against batches of text data, returning a model's multidimensional representation of said features
in tensor/float64 format.


` + description
```

Think the way you have it like that - means that there is no spaces between the sentences, if you want the sentences to appear on a separate line - then you can alter my suggestion such there is two blank lines rather than 1.

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_token_classification.go
> +		Description(tokenClassificaitionDescription).
```suggestion
	tokenClassificationDescription := `### Token Classification
Token classification assigns a label to individual tokens in a sentence.
This processor runs token classification inference against batches of text data, returning a set of Entities classification corresponding to each input.


` + description

	spec := hugotConfigSpec().
		Summary("Performs token classification using a Hugging Face 🤗 NLP pipeline with an ONNX Runtime model.").
		Description(tokenClassificationDescription).
```

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_token_classification.go
> +		Description(tokenClassificaitionDescription).
formatting of md and typo in tokenClassificationDescription

2025-07-18 17:01 UTC, jem-davies commented on internal/impl/huggingface/processor_zero_shot_classification.go
> +		description
```suggestion
	textClassificationDescription := `### Zero Shot Text Classification
	
Zero-shot text classification allows you to classify text into any labels without training on those specific labels.
It uses Natural Language Inference (NLI) models to determine if a text entails each candidate label.
This is more flexible than regular text classification as labels can be chosen at runtime, but may be slower.
Common use cases include sentiment analysis, topic classification, intent detection, and content moderation.


` + description
```

2025-08-24 12:24 UTC, gregfurman commented on internal/impl/huggingface/processor.go
> +		if filepath.Ext(modelPath) != "" {
Good spot ☝️

2025-08-24 12:27 UTC, gregfurman commented on internal/impl/huggingface/processor.go
> +type SessionConstructor func() (*hugot.Session, error)
Was originally exported since I was running the tests in a seperate test package. Can be made private now though. Thanks 😄

2025-08-24 12:36 UTC, gregfurman commented on internal/impl/huggingface/processor_text_classification.go
> +		description
I prefer the joined together version since otherwise it stretches too far across screen tbh. I assume this isn't blocking?

2025-08-24 12:42 UTC, jem-davies commented on internal/impl/huggingface/processor_text_classification.go
> +		description
I think that I raised this because of how it looks on the doc site iirc. - it's from the other comment: 

"""
Think the way you have it like that - means that there is no spaces between the sentences, if you want the sentences to appear on a separate line - then you can alter my suggestion such there is two blank lines rather than 1.
"""

2025-08-24 12:43 UTC, jem-davies commented on internal/impl/huggingface/processor_text_classification.go
> +		description
You could keep it like that but I think the problem is there isn't spaces between the sentences, and the \n won't give a line break - you would need two of them \n\n (think that's a markdown thing...)

2025-08-24 12:44 UTC, gregfurman commented on internal/impl/huggingface/processor_text_classification.go
> +		description
Should be fixed now I think 🤔

2025-08-24 16:24 UTC, RJKeevil commented
Just an FYI im hoping this week to do a large release of hugot with textGeneration, crossEncoder and imageClassification pipelines also, will ping here when it is out in case those are of interest!

2025-08-25 10:37 UTC, merged

2025-08-30 14:10 UTC, RJKeevil commented
@gregfurman @jem-davies Hugot v0.5.2 is now out, so if you want to upgrade and enable image classissication or cross encoders at some point it is ready. We also added text generation for generative models, but it requires the C dependencies for now until some additional operators are added to goMLX.

2025-08-30 14:44 UTC, gregfurman commented
> @gregfurman @jem-davies Hugot v0.5.2 is now out, so if you want to upgrade and enable image classissication or cross encoders at some point it is ready. 

@RJKeevil OK awesome! Will give a look at implementing this.

> We also added text generation for generative models, but it requires the C dependencies for now until some additional operators are added to goMLX.

Do you have an issue tracking these additional operators? As an aside, wonder if it'll be worthwhile to include the ONNX runtime in the CGO build 🤔 

Otherwise, have you had a chance to try the new Hugot components? Check out the docs here: https://warpstreamlabs.github.io/bento/docs/components/processors/nlp_classify_text/

2025-08-31 08:53 UTC, RJKeevil commented
I'll coordinate with Jan on what operators are missing and get an issue raised on goMLX, I think it may also be tied to a bigger change of moving to stableHLO, which i know he is plaaning but will be a large (but important) change.

Adding ORT would be great if possible, as it is much faster than pure go, and is usually more compatible with different models (more mature and the weight of a large company behind it). So at least it is a great alternative option if you can live with the extra build complexity.

I havent myself had time to play around with Bento but i'd love to, will give it a try when i get a second!

2025-09-01 15:08 UTC, RJKeevil commented
@gregfurman v0.5.3 released today should come with a decent speed boost to the go backend, around 25% on my tests. Interested what you observe. We also made a blog post today about what were up to if youre interested https://www.knightsanalytics.com/post/gomlx-and-hugot-expanding-the-horizons-of-machine-learning-in-go