Add QuestDB output component
warpstreamlabs/bento pull request #115
Opened 2024-09-13 14:40 UTC by sklarsa

Adds an output component for writing to [QuestDB](https://questdb.io/) tables using ILP (Influx Line Protocol) as implemented by the official [QuestDB Go Client](https://github.com/questdb/go-questdb-client).

2024-09-14 12:27 UTC, gregfurman requested changes
Thanks for submitting this! All is looking good just some minor clarifications and suggestions.

Also, have you used QuestDB against our existing SQL components? Would be curious if it works out-the-box it and would be happy to extend them if need to do accomodate QuestDB!

Otherwise, your tests are passing on my local but I haven't (yet) tested this against a running QuestDB instance. Will do so soon 🥇

2024-09-14 12:27 UTC, gregfurman commented on internal/impl/questdb/output.go
> +	releaseErr := sender.Close(ctx)
nit: Assume we always want to close the Sender? Maybe consider a `defer` call. 

Also do we want to consider the entire batch a failure if this fails to close/flush? If not, maybe we should do a fire-and-forget with a goroutine.

2024-09-16 17:39 UTC, sklarsa commented on internal/impl/questdb/output.go
> +	if conf.Contains("username") && conf.Contains("password") {
I wanted to reduce code complexity here by letting the client take care of the precedence and just worry about properly parsing the args in this section.  I'm happy to make any changes for clarity if you feel that's necessary.

2024-09-16 17:41 UTC, sklarsa commented on internal/impl/questdb/output.go
> +				Optional(),
Thanks! I actually borrowed this from our [Kafka connector configuration options](https://questdb.io/docs/third-party-tools/kafka/questdb-kafka/#configuration-manual). We don't have any more types that we need to support at the moment.

2024-09-16 17:51 UTC, sklarsa commented on internal/impl/questdb/output.go
> +	releaseErr := sender.Close(ctx)
I think we want to consider the entire batch a failure since it's basically impossible to know (from the client's perspective) which rows successfully made it and which did not. This is why we suggest that you enable dedupe on the server side, so you can retry the entire batch and not have to worry about the results of the first attempt.

I like the defer suggestion, will implement it now

2024-09-16 17:57 UTC, sklarsa commented
> Also, have you used QuestDB against our existing SQL components? Would be curious if it works out-the-box it and would be happy to extend them if need to do accomodate QuestDB!

I have not. We implement pgwire and should be compatible with standard postgres clients. I'll give that a shot this week, although we really only recommend using SQL for data extraction and querying, not ingestion.

2024-09-17 17:39 UTC, gregfurman commented on internal/impl/questdb/output.go
> +	if conf.Contains("username") && conf.Contains("password") {
Yeah that makes sense. Wasn't sure what the client did internally but if it handles both the auth token and credentials being passed in then happy to leave it as-is

2024-09-17 17:42 UTC, gregfurman commented on internal/impl/questdb/output.go
> +}
OK sick! Thanks for linking the above. Feel free to open an issue to track adding this 🚀

2024-09-17 17:44 UTC, gregfurman commented on internal/impl/questdb/output.go
> +	qdb.WithMaxSenders(mif)(w.pool)
Quick update here: not sure about the above. Have asked Jem to take a look.

What other value would make sense for the sender count?

2024-09-17 18:01 UTC, sklarsa commented on internal/impl/questdb/output.go
> +	qdb.WithMaxSenders(mif)(w.pool)
The pool defaults to a maximum of 64 senders. Ideally, we would use a sender per bento thread/goroutine, but it's not clear to me how many concurrent executions of `WriteBatch` can happen at a single time. I'm guessing `max_in_flight` is a maximum message count then?

2024-09-17 18:50 UTC, jem-davies commented on internal/impl/questdb/output.go
> +	qdb.WithMaxSenders(mif)(w.pool)
I think the max_in_flight is how many messages will be processed concurrently by the output component. That it will create a new goroutine for each message up to the point it wouldn't over go over this limit.

2024-09-17 18:57 UTC, jem-davies commented on internal/impl/questdb/output.go
> +	qdb.WithMaxSenders(mif)(w.pool)
I can take a look tomorrow - just busy at the moment

2024-09-17 20:08 UTC, gregfurman commented on internal/impl/questdb/output.go
> +	qdb.WithMaxSenders(mif)(w.pool)
Yeah it's a maximum message count. Happy with approving and seeing how performance looks, and iterating on this at another point

2024-09-17 20:11 UTC, gregfurman commented
Lastly, can you add the docs for the component? Running [`make docs`](https://github.com/warpstreamlabs/bento/blob/main/Makefile#L111) should suffice 🙂 

Once that's added I'll approve and we can ship this bad-boy

2024-09-17 20:31 UTC, sklarsa commented
>Lastly, can you add the docs for the component? Running [make docs](https://github.com/warpstreamlabs/bento/blob/main/Makefile#L111) should suffice 🙂

Done! Thank you :-)

2024-09-18 15:14 UTC, gregfurman approved these changes
LGTM! Just fixed the formatting of that description string.

2024-09-18 15:15 UTC, merged