add output cypher component
warpstreamlabs/bento pull request #118
Opened 2024-09-17 12:17 UTC by jem-davies

2024-09-17 20:19 UTC, gregfurman requested changes

2024-09-17 20:19 UTC, gregfurman commented on cmd/bento/config.yaml
Think this should be removed

2024-09-17 20:19 UTC, gregfurman commented on internal/impl/cypher/output_cypher.go
> +				Default(true),
Maybe this should be removed for now since it doesn't look like it's being used?

2024-09-17 20:19 UTC, gregfurman commented on internal/impl/cypher/output_cypher.go
> +		_, err := neo4j.ExecuteQuery(ctx, cyp.driver,
Should this output be a `query` or an `INSERT` statement of some kind? I'd imagine a`SELECT` (or neo4j equivalent) shouldn't be processed as output

2024-09-17 20:19 UTC, gregfurman commented on internal/impl/cypher/output_cypher.go
> +	query, err := conf.FieldString("query")
Just a thought but I wonder if this should be sanitised in some way to prevent some query injection

2024-09-28 19:33 UTC, jem-davies commented on cmd/bento/config.yaml
taken it out

2024-09-28 19:34 UTC, jem-davies commented on internal/impl/cypher/output_cypher.go
> +				Default(true),
added a field for basic_auth so it is being used now

2024-09-28 19:35 UTC, jem-davies commented on internal/impl/cypher/output_cypher.go
> +		_, err := neo4j.ExecuteQuery(ctx, cyp.driver,
I think there is a few different verbs that can create data - so with this approach, yes you could add the equivalent of a select but I think that is more on the user at that point.

2024-09-28 19:35 UTC, jem-davies commented on internal/impl/cypher/output_cypher.go
> +	query, err := conf.FieldString("query")
I think that should be ok - as is.

2024-09-29 11:15 UTC, gregfurman requested changes
Looking good. Have left some comments and nits. Haven't validated the tests on my local though but will do so soon.

2024-10-02 20:12 UTC, jem-davies commented on internal/impl/cypher/output_cypher_test.go
> +	neo4jDockerAddress := fmt.Sprintf("bolt://localhost:%s", resource.GetPort("7687/tcp"))
refactored the tests so they are similar to etcd 👍  -- also I think that the docker engine will only assign to a free port anyway.

2024-10-02 20:13 UTC, jem-davies commented on internal/impl/cypher/output_cypher.go
> +func validateQueryAndValues(query string, values map[string]*service.InterpolatedString) error {
There are TestCypherOutputMissingValue and TestCypherOutputMissingParam in output_cypher_test.go - have you seen them / they not what we will want?

2024-10-02 21:01 UTC, jem-davies commented
@gregfurman thanks for review - updated the code / responded to your comment...

2024-10-05 16:51 UTC, gregfurman reviewed
This is looking great, dude! Just some comments regarding tests (setup + teardown, properly passing around the `testing.T` and adding a batching test).

Also ran your tests and my local and all looks good 👍

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher.go
> +The ` + "`" + `query` + "`" + ` field is expected to be a valid cypher query with 0 or more parameters with the $ syntax:
```suggestion
The ` + "`" + `query` + "`" + ` field is expected to be a valid cypher query with 0 or more parameters with the ` + "`" + `$` + "`" + `syntax:
```

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher.go
> +      CREATE (p:Person {name: $name}) RETURN p
Should we not just allow bloblang mappings directly in here instead of that extra values field?

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher_test.go
> +	neo4jDockerAddress := fmt.Sprintf("bolt://localhost:%s", resource.GetPort("7687/tcp"))
I get you. However, if we ran 2 tests concurrently and tried to call `resource.GetPort("7687/tcp")` when both containers were running (each internally assigned the same port) then we would've run into a similar issue as with etcd. 

I see you addressed this though 😄

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher_test.go
> +		x := dictionary["n"].(dbtype.Node)
nit: Maybe don't use `x` lol

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher_test.go
> +	sendMessages(&testing.T{}, s)
You need to pass the `testing.T` fixture to these sub-tests, otherwise we'll have issues with test context
```suggestion
	sendMessages(t, s)
```

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher_test.go
> +	sendMessages(&testing.T{}, s)
```suggestion
	sendMessages(t, s)
```

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher_test.go
> +func setupNeo4j(env []string) (string, error) {
If you add a `t.Testing` fixture up here, you can ensure that the resource is purged when the test is done, as opposed to relying on that `resource.Expire()` call.

```
	require.NoError(t, err)
	t.Cleanup(func() {
		assert.NoError(t, pool.Purge(resource))
	})
```

Could also do assertions up here with `require.NoError(t, err)` and just return a `string` instead of worrying about returning an error type and checking if its not nil.

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher.go
> +func NewCypherOutputFromConfig(conf *service.ParsedConfig, mgr *service.Resources) (*CypherOutput, error) {
Assuming we're going to write an `insert` as well, we should consider adding `metadata` when streaming in input

2024-10-05 16:51 UTC, gregfurman commented on internal/impl/cypher/output_cypher_test.go
> +    count: 0
Any chance we can just have a single test with batching?

2024-10-06 11:01 UTC, jem-davies commented on internal/impl/cypher/output_cypher.go
> +      CREATE (p:Person {name: $name}) RETURN p
Think it's like this because this is how the func [ExecuteQuery](https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j#ExecuteQuery) is in the neo4j package + it is similar to how the sql_insert is done with the args_mapping field.

2024-10-06 11:23 UTC, jem-davies commented on internal/impl/cypher/output_cypher.go
> +func NewCypherOutputFromConfig(conf *service.ParsedConfig, mgr *service.Resources) (*CypherOutput, error) {
unsure what you mean? (did you mean `input` instead of `insert`) 

I think yeah we def. could add some metadata fields as done with a lot of the components, think that some follow on PRs will come after this for an input / more functionality, maybe we add that in later on?

2024-10-06 13:37 UTC, jem-davies commented on internal/impl/cypher/output_cypher_test.go
> +    count: 0
added in

2024-10-06 13:37 UTC, jem-davies commented on internal/impl/cypher/output_cypher_test.go
> +func setupNeo4j(env []string) (string, error) {
updated them

2024-10-06 13:40 UTC, jem-davies commented
@gregfurman addressed the last batch of feedback, thanks

2024-10-31 20:53 UTC, gregfurman commented on internal/impl/cypher/output_cypher.go
> +func NewCypherOutputFromConfig(conf *service.ParsedConfig, mgr *service.Resources) (*CypherOutput, error) {
I meant like assuming we are going to write a `cypher_insert` similar to `sql_insert` since this component is equivalent to `sql_raw`. But yeah let's get this bad-boy in.

2024-10-31 20:55 UTC, gregfurman approved these changes
LGTM! Sorry for taking so long on this one 😄

2024-11-06 00:06 UTC, merged