add: strict mode for Logger component
warpstreamlabs/bento pull request #143
Opened 2024-10-29 18:27 UTC by gregfurman

Adds an optional wrapped logger that will promote any log with an `error` type to the `ERROR` level.

This does not include ading an error in a logger's `With` or `WithField`.

For example, if you set:

```yaml
logger:
    strict: true
```

Then any subsequent `logger` calling `Warn`, `Info`,`Debug`, `Trace`, or with an `error` type in the params will promote the log to an `Error` type.

In addition, a field `@strict=true` is added to all logs generated from the strict logger:

```go
level=error msg="Trace message root module: fail" @service=bento_service @strict=true
```

2024-10-29 18:46 UTC, richardartoul approved these changes
LGTM with a few comments

2024-10-29 18:46 UTC, richardartoul commented on internal/log/strict.go
> +		switch arg.(type) {
I think you probably want something like this:

```golang
_, isErr := arg.(error)
```

instead to see if it implements the error interface, not if its literally an error no?

2024-10-29 18:46 UTC, richardartoul commented on internal/log/config.go
> +	fieldStrictLogging    = "strict"
`log_all_errors` IMO instead of "strict" since thats way more clear

2024-10-29 18:46 UTC, richardartoul commented on internal/log/config.go
> +	fieldStrictLogging    = "strict"
Update all the variables / go code to match the name as well

2024-10-29 21:57 UTC, gregfurman commented on internal/log/strict.go
> +		switch arg.(type) {
Wont the switch case also check if the value `arg` implements the `error` interface? 

Or are you suggesting we remove the check for `*error` as well since that's _technically_ not an `error` type.

2024-10-29 22:05 UTC, gregfurman commented on internal/log/config.go
> +	fieldStrictLogging    = "strict"
Done!

2024-10-30 03:16 UTC, richardartoul commented on internal/log/strict.go
> +		switch arg.(type) {
I guess if your tests pass its fine

2024-10-30 03:17 UTC, richardartoul approved these changes

2024-10-30 03:18 UTC, richardartoul approved these changes

2024-10-30 03:18 UTC, richardartoul commented on internal/log/strict.go
> +package log
rename this file

2024-10-30 03:18 UTC, richardartoul commented on internal/log/strict_test.go
> +package log
rename this file

2024-10-30 03:18 UTC, richardartoul commented on internal/log/strict_test.go
> +func TestStrictLogger(t *testing.T) {
rename this test

2024-10-30 17:54 UTC, jem-davies commented
I acknowledge the request for review - will give it a good look soon 👍

2024-11-07 20:02 UTC, jem-davies commented on website/docs/components/logger/about.md
> +Requires version 1.3.0 or newer
```suggestion
Requires version 1.4.0 or newer  
```

2024-11-07 20:03 UTC, jem-davies commented on internal/log/docs.go
> +		docs.FieldBool(fieldLogAllErrors, "Experimental: When set, the logger will promote any log containing an `error` type to the `ERROR` level.").HasDefault(false).Advanced().AtVersion("1.3.0"),
```suggestion
		docs.FieldBool(fieldLogAllErrors, "Experimental: When set, the logger will promote any log containing an `error` type to the `ERROR` level.").HasDefault(false).Advanced().AtVersion("1.4.0"),
```

I forgot to check on the cypher output 🤕

2024-11-07 20:14 UTC, jem-davies commented on internal/log/config.go
> +	fieldLogAllErrors     = "log_all_errors"
I think that something like `promote_errors` is a better name, because that is more descriptive of what this field does? Taken the word promote from the description you have written.

2024-11-07 20:28 UTC, jem-davies commented on internal/log/config.go
> +	fieldLogAllErrors     = "log_all_errors"
I might think that like `log_all_errors` takes the message contents and logs any/all errors in the message data?

2024-11-07 21:24 UTC, jem-davies requested changes
LGTM - just the version number

2024-11-12 16:28 UTC, jem-davies approved these changes

2024-11-12 16:36 UTC, merged