add: LIFO option to dedupe processor
warpstreamlabs/bento pull request #148
Opened 2024-10-31 18:40 UTC by gregfurman

### Changes

- Adds the ability to de-duplicate values in FIFO or LIFO order (FIFO by default.). 
- Adds a `strategy` key where this value can be set.

2024-11-04 22:18 UTC, jem-davies requested changes
LGTM - just a small nit pick in the code

2024-11-05 09:00 UTC, gregfurman commented on internal/impl/pure/processor_dedupe.go
> +			}
I did this since I wanted the code to be self-documenting about what types could be selected. I suppose it's not entirely necessary so happy to make this more concise

2024-11-05 23:23 UTC, jem-davies commented on internal/impl/pure/processor_dedupe.go
> +			}
I see that yeah - guess I just read the config spec first and saw it was an enum anyway - then thought this switch statement looked a bit unnecessary. 

Ill resolve the thread, up to you if you want to use the suggestion or not.

2024-11-05 23:24 UTC, jem-davies approved these changes

2024-11-05 23:24 UTC, jem-davies commented
approving the changes now , but if you want to take the suggestion then take it.

2024-11-07 08:09 UTC, merged