add: IAM RDS auth to sql components and refactor
warpstreamlabs/bento pull request #168
Opened 2024-11-17 22:09 UTC by gregfurman

### Changes
- Refactors how AWS components are imported -- allowing for Bento distros without the AWS SDK to compile and use  SQL components.
- Adds support for generating an IAM authentication token for RDS.
- Some more refactoring to make both secret manager and IAM approaches better integrated.

###  TODO
- Some integration testing using[ LocalStack against RDS with IAM](https://docs.localstack.cloud/user-guide/aws/rds/#iam-authentication-support).

2025-02-21 15:47 UTC, jem-davies approved these changes
LGTM

2025-02-22 09:16 UTC, gregfurman commented on internal/impl/sql/conn_fields.go
> +					Description("An optional field that can be used to get the Username + Password from AWS Secrets Manager. This will overwrite the Username + Password in the DSN with the values from the Secret on
@jem-davies We should make a note that this field has changed to within the `aws` config section

2025-03-27 12:11 UTC, jem-davies requested changes
let's block the merge button until we have communicated the breaking changes

2025-05-07 11:45 UTC, jem-davies commented
@gregfurman we happy to merge this then now?

2025-05-10 16:10 UTC, jem-davies requested changes

2025-05-10 16:10 UTC, jem-davies commented on internal/impl/sql/integration_test.go
> +func TestIntegrationRdsIamAuth(t *testing.T) {
Currently failing

2025-05-10 18:58 UTC, jem-davies commented on internal/impl/sql/integration_test.go
> +func TestIntegrationRdsIamAuth(t *testing.T) {
Tested on AWS manually: 

Ran the ./rdsIamAuth.tf - against actual aws - created a iam user with policy: 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "*"
            ],
            "Resource": [
                "arn:aws:rds-db:us-east-1:000000000000:dbuser:db-XXXXXXXXXXXXXXXXXXXXXXXXXX/db_userx"
            ]
        }
    ]
}
```

Created a new user via psql: 

```
CREATE USER db_userx;
GRANT rds_iam TO db_userx;
GRANT ALL ON ALL TABLES IN SCHEMA public TO db_userx;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO db_userx;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO db_userx;
GRANT USAGE ON SCHEMA public TO db_userx;
GRANT CREATE ON SCHEMA public TO db_userx;
ALTER SCHEMA public OWNER TO db_userx;
```

Ran the following Bento config from source: 

```yaml
input:
  generate:
    mapping: |
        root = {"age":random_int(min: 0, max: 100), "name":fake("name")}
    interval: 1ms
    count: 10
  
output:
  sql_insert:
    driver: postgres 
    dsn: postgresql://db_userx:password@my-rds-instance.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com:5432/testdb
    table: test
    columns: [age, name]
    args_mapping: |
      root = [
        this.age,
        this.name,
      ]
    iam_enabled: true
    init_statement: "CREATE TABLE test (name varchar(255), age int);"
   ```

```
select * from test;

          name           | age 
-------------------------+-----
 Lord Leif Cummings      |  59
 Lord Andres Hills       |  28
 Mr. Tremayne Heaney     |   9
 Mr. Junius Turcotte     |  23
 Prof. Cielo Botsford    |  47
 King Geovanny Armstrong |  15
 King Art Johnson        |  55
 Prof. Deonte Mayer      |  63
 Mr. Hilario Glover      |  46
 Dr. Caesar Pagac        |  32
```

2025-05-10 21:16 UTC, jem-davies commented on internal/impl/sql/conn_fields.go
> +			Version("1.8.0").
You would have `secret_name` set to something other than `""` - and you would leave `iam_enabled` default false - should be ok with existing configs - the integration test for the secret replacement has a config like:

```yaml
output:
  sql_insert:
    driver: postgres 
    dsn: postgresql://username_from_secret:password_from_secret@%v/dev?sslmode=disable
    table: test
    columns: [age, name]
    args_mapping: |
      root = [
        this.age,
        this.name,
      ]
    init_statement: "CREATE TABLE test (name varchar(255), age int);"
    secret_name: "redshift-password"
    region: us-east-1
    endpoint: http://localhost:%v
    credentials:
      id: test
      secret: test
```

2025-05-10 21:19 UTC, gregfurman reviewed
Built bento on my local w/out the AWS package imported, which should work with these changes.

Once you confirm this works for you, happy to merge this bad boy! (I can't approve since I opened)

2025-05-10 21:20 UTC, jem-davies commented
> Built bento on my local w/out the AWS package imported, which should work with these changes.
> 
> Once you confirm this works for you, happy to merge this bad boy! (I can't approve since I opened)

yeah good shout ill do another test tomorrow with a custom build to double check too

2025-05-11 12:49 UTC, merged