Add backoff and error payload sampling to error handling bundle
warpstreamlabs/bento pull request #189
Opened 2024-12-16 16:17 UTC by gregfurman

## Changes

- Adds an `ErrorSampleBundle` that will randomly select a proportion of failed events and log them -- allowing us to see the payload of those events that failed processing.
- Adds a `RetryBundle` that will retry failed processing steps with exponential backoff -- closing the input layer while retrying.

## Examples

### Errored Payload Sampling
The below will log a proportion of all failed payloads:
```yaml
error_handling:
  error_sample_rate: 0.5
```

### Retry with backoff

```yaml
error_handling:
  strategy: backoff
  max_retries: 0 # default is 0. Otherwise, 0 or less means we will retry forever.
```

## TODO
[ ] Add configuration tests for the new `error_handling` fields.
[ ] Add mocked tests for `error_sample_rate`.
[ ] Validations for `max_retries` field.

2024-12-22 19:48 UTC, jem-davies reviewed
will do another look at the processors but seems ok to me

2024-12-24 12:59 UTC, gregfurman commented on internal/bundle/strict/bundle.go
> +		_ = env.InputAdd(func(conf input.Config, nm bundle.NewManagement) (input.Streamed, error) {
I was following the lead of the other `tracing` bundle -- where this is done.

Thinking to leave as anonymous function since it's very specialised to the initialisation/overloading and can't really imagine it being used elsewhere.

2024-12-27 12:56 UTC, jem-davies commented on internal/cli/common/manager.go
> +	if conf.ErrorHandling.Strategy != "none" || conf.ErrorHandling.ErrorSampleRate > 0 {
Yeah I think checking it like this is fine

2024-12-27 13:06 UTC, gregfurman commented on internal/cli/common/manager.go
> +	if conf.ErrorHandling.Strategy != "none" || conf.ErrorHandling.ErrorSampleRate > 0 {
OK sick. FYI, I made this `"none"` because that was used by `buffer` and some other components to indicate a disabled type. Changing this though yo `""`

2024-12-27 13:07 UTC, gregfurman commented on internal/cli/common/manager.go
> +	if conf.ErrorHandling.Strategy != "none" || conf.ErrorHandling.ErrorSampleRate > 0 {
OK sick. FYI, I made this `"none"` because that was used by `buffer` and some other components to indicate a disabled type. Changing this to `""` though :)

2024-12-27 21:57 UTC, jem-davies requested changes
I think there is an issue with the description of the `backoff` / `max_retries` - about the dropping of messages but it doesn't drop messages like the `reject` strategy? - it will continue along the pipeline after doing the max_retries?

I think it would be better as well if the content on [/components/processors/about#error-handling](https://warpstreamlabs.github.io/bento/docs/components/processors/about#error-handling) was moved to [/docs/configuration/about](https://warpstreamlabs.github.io/bento/docs/configuration/about) because this is where the other top level config options such as `shutdown_delay` are described? 

I noticed that there is a relative link to `error-handling` [here](http://localhost:3000/bento/docs/components/processors/about#error-handling) when it should probably be [error-handling-1](http://localhost:3000/bento/docs/components/processors/about#error-handling-1) it's a bit confusing because there are two headings both 'error-handling'? 

I think as well that there isn't enough explanation in the docs currently about the backoff strategy - about how that will block input and the default options for the:

```go
backoffCtor := func() backoff.BackOff {
		boff := backoff.NewExponentialBackOff()
		boff.InitialInterval = time.Millisecond * 100
		boff.MaxInterval = time.Second * 60
		boff.MaxElapsedTime = 0
		return boff
	}
```

2024-12-27 21:57 UTC, jem-davies commented on internal/bundle/strict/processor_sample_error.go
> +				}
I think we could just return the `raw_payload` field and not worry about marshalling it to json then returning either a `structured_payload` / `structured_payload_error` field, just because it's an assumption to make, that it will be a json message, it might not be, (could be a csv row) and marshalling every message part in a loop could be resource intensive. 

It probably makes sense to add a field to enable or disable these `structured_payload` / `structured_payload_error` fields because it sounds contextual to specific application of Bento to me?

2024-12-27 21:57 UTC, jem-davies commented on internal/errorhandling/docs.go
> +		docs.FieldInt(fieldMaxRetries, "Maximum retries before dropping a message for a `backoff` strategy. `0` indicates indefinite retries.").HasDefault(0).
"Maximum retries before dropping a message for a `backoff` strategy." This took me a while to understand after reading the source for processor_retry.go. 

I think that it would be better if we could look at making it so that a config like:

```yaml
error_handling:
  strategy: reject
  max_retries: 2
```

Would fail initialising because the `max_retries` is only for `strategy: backoff`? 

Also where it says: "retries before _dropping_ a message" - the messages don't get dropped when using this strategy, they get retried X times, then they continue with errors so a config like: 

```yaml
error_handling:
  strategy: backoff
  max_retries: 2

pipeline:
  processors:
    - mapping: |
        root = throw("error")
    - mapping: | 
        root.message = "I'm never reached"
```

Would do this: 

```
{}
ERRO failed assignment (line 1): error             @service=bento label="" path=root.pipeline.processors.0
ERRO failed assignment (line 1): error             @service=bento label="" path=root.pipeline.processors.0
ERRO failed assignment (line 1): error             @service=bento label="" path=root.pipeline.processors.0
{"message":"I'm never reached"}
```

2024-12-28 14:25 UTC, gregfurman commented on internal/errorhandling/docs.go
> +		docs.FieldInt(fieldMaxRetries, "Maximum retries before dropping a message for a `backoff` strategy. `0` indicates indefinite retries.").HasDefault(0).
> Would fail initialising because the `max_retries` is only for `strategy: backoff`?

Yeah happy to add a linting check to this.

> Also where it says: "retries before dropping a message" - the messages don't get dropped ...

Oh yeah that is correct. Definitely an oversight on my end. Should we drop messages or do you think continuing as it currently does is sufficient?

2024-12-28 16:15 UTC, gregfurman commented on internal/bundle/strict/processor_sample_error.go
> +				}
I don't think we should worry about overhead tbh. If resource intensivity is an issue, a user can just sample a smaller proportion of failed payloads.

If I read in CSV data, don't we convert this to a JSON friendly format anyway when constructing messages? So the structured payload will still correctly show CSV data but just in JSON/structured form

2024-12-30 12:50 UTC, jem-davies approved these changes

2024-12-30 12:58 UTC, jem-davies commented on website/docs/configuration/about.md
> +| `backoff` | Retries batches containing failed messages using exponential backoff. Starting at `100ms`, the delay doubles after each retry up to a maximum of `60s` between attempts. When `max_retrie
```suggestion
| Strategy | Version | Description |
|----------|-------------|-------------|
| `reject` | v1.4.0 |Immediately fails entire batch when any message has an error. Propagates negative acknowledgment (nack) to the input. |
| `backoff` | v1.5.0 |Retries batches containing failed messages using exponential backoff. Starting at `100ms`, the delay doubles after each retry up to a maximum of `60s` between attempts. When `max_retries` is `0` (default), retries continue indefinitely. Otherwise, messages are dropped from the batch after the maximum retries are exhausted. |
```

Think would be good to add a version column for the strategies.

2025-03-08 14:46 UTC, gregfurman commented
Closed in favour of https://github.com/warpstreamlabs/bento/pull/221

2025-03-08 14:46 UTC, closed without merging