Serverless housekeeping: Local testing guide, small docs fixes, and some handler tests for errors
warpstreamlabs/bento pull request #62
Opened 2024-06-29 15:29 UTC by gregfurman

Some small fixes/improvements:
- Added some serverless handler tests
- Included short guide on local testing AWS `bento-lamba` using LocalStack 
- Added note on batches failing when exceptions are not caught (from https://github.com/warpstreamlabs/bento/issues/59#issuecomment-2195654914)

2024-07-02 20:01 UTC, jem-davies commented on website/docs/guides/serverless/lambda.md
> +
```suggestion
:::caution
Note: if you are using [partial batch responses](https://docs.aws.amazon.com/lambda/latest/dg/services-sqs-errorhandling.html#services-sqs-batchfailurereporting) then 
throwing an exception will cause the entire batch to be considered a failure.
:::
```

Can do this for increased visibility.

2024-07-02 20:39 UTC, jem-davies commented on website/docs/guides/serverless/lambda.md
> +To run commands against LocalStack, just [configure the endpoint URL](https://docs.localstack.cloud/user-guide/integrations/aws-cli/#configuring-an-endpoint-url) `--endpoint-url=<localstack-url>` fla
```suggestion
First, set your AWS CLI to connect to LocalStack:
```sh
export AWS_ACCESS_KEY_ID="test"
export AWS_SECRET_ACCESS_KEY="test"
export AWS_DEFAULT_REGION="us-east-1"
export AWS_ENDPOINT_URL=http://localhost:4566
```
```

2024-07-02 20:39 UTC, jem-davies commented on website/docs/guides/serverless/lambda.md
> +  --endpoint-url http://localhost:4566
```suggestion
```

2024-07-02 20:39 UTC, jem-davies commented on website/docs/guides/serverless/lambda.md
> +  --endpoint-url http://localhost:4566 \
```suggestion
```

2024-07-02 20:40 UTC, jem-davies commented on website/docs/guides/serverless/lambda.md
> +  --endpoint-url http://localhost:4566 \
you can do it this way - not a big deal but I think it just cuts down slightly on amount of text.

2024-07-02 20:42 UTC, jem-davies commented on website/docs/guides/serverless/lambda.md
don't think I can add a comment to a line that hasn't been altered, 

One line 158 there is a mistake `amd64` -> `arm64`?

2024-07-02 20:57 UTC, jem-davies requested changes
looks good to me - just a few nitpicky things - feel free to ignore them if you think it better how it is 👍

2024-07-02 20:57 UTC, jem-davies commented on internal/serverless/handler_test.go
> +	// TODO: Should this not be failing since an exception is thrown?
Looks right to me - is testing the behaviour [here](http://localhost:3000/bento/docs/guides/serverless/lambda#processing-errors)

It is throwing an error in the pipeline.processor part of the config so what we should see is: 

 - not see an error 
 - get the final state of the message

```suggestion
```

2024-07-03 08:33 UTC, gregfurman commented on website/docs/guides/serverless/lambda.md
> +To run commands against LocalStack, just [configure the endpoint URL](https://docs.localstack.cloud/user-guide/integrations/aws-cli/#configuring-an-endpoint-url) `--endpoint-url=<localstack-url>` fla
I like using the environment variable instead. I'll make a comment that it should be unset though before wanting to actually create a resource in AWS.

2024-07-03 08:47 UTC, jem-davies approved these changes

2024-07-03 09:15 UTC, merged