Upstream changes
warpstreamlabs/bento pull request #65
Opened 2024-07-03 22:03 UTC by jem-davies

2024-07-04 14:41 UTC, gregfurman commented
Hey. Haven't given a proper look at changes yet but If possible, maybe remove or rename the merge commits `84093c7` and `524991e`.

2024-07-05 14:49 UTC, gregfurman requested changes
Good stuff, @jem-davies -- no doubt this was a gnarly one to work through. A couple of things:
- Some upstream naming changes
- Commits being added should be cleaned up a bit
- Question re: new introduced `max_retry` config

2024-07-05 14:49 UTC, gregfurman commented on internal/manager/mock/manager.go
> +// benthos engine.
```suggestion
// bento engine.
```

2024-07-05 14:49 UTC, gregfurman commented on internal/config/test/case.go
> +// Case contains a definition of a single Benthos config test case.
```suggestion
// Case contains a definition of a single Bento config test case.
```

2024-07-05 14:49 UTC, gregfurman commented on internal/manager/input_wrapper.go
> +// the wrapped input\.
```suggestion
// the wrapped input.
```

2024-07-05 14:49 UTC, gregfurman commented on internal/bloblang/query/methods_strings.go
nit: do we to be referencing issues in commit messages not in the upstream repo here?

2024-07-05 14:49 UTC, gregfurman commented on internal/impl/pure/processor_retry.go
> +				Default(0),
Hmm... so is it possible to disable retries? Not sure if it's ever ideal to but `0` resulting in infinite is an interesting choice. Maybe we should rather set to unbounded if unset and disable if 0?

2024-07-05 14:49 UTC, gregfurman commented on CHANGELOG.md
This commit `074bf424` and the next commit `84093c71` should probably be dropped

2024-07-12 19:35 UTC, jem-davies commented on internal/impl/pure/processor_retry.go
> +				Default(0),
See what you are saying, but would rather just take them as is - feel that is less complicated for future?

2024-07-13 09:45 UTC, gregfurman commented
Couple of things:
- Can you run a `git rebase` and squash/reword commits where possible?
- I see some commits are unverified so make sure all is signed. Lmk if you need help with that because I know rebase + signing is a mission.
- I know it's a tall ask but can you try summarise the changes introduced in the PR description? I'd check in the `CHANGELOG.old.md` (should be renamed to `CHANGELOG.upstream.md` imo) and see what entries are relevant. It could even be worth cherry-picking from releases instead of from `main`...

2024-07-14 12:35 UTC, gregfurman requested changes

2024-07-14 12:35 UTC, gregfurman commented on internal/bloblang/query/methods_test.go
Is there a commit with these changes [2f2c0cc](https://github.com/warpstreamlabs/bento/pull/65/commits/2f2c0ccb0a31712c63adde663d5a61d0ecda4766) that is not a `merge` commit? Think we should use that instead especially since this is referencing a non-existent PR.

2024-07-14 12:35 UTC, gregfurman commented on internal/component/connection.go
Wow this is awesome. Definitely need to keep an eye on this package.

2024-07-14 12:35 UTC, gregfurman commented on internal/bloblang/query/methods_strings.go
> nit: do we to be referencing issues in commit messages not in the upstream repo here?

Look at this commit message again [6d7e792](https://github.com/warpstreamlabs/bento/pull/65/commits/6d7e792bcb8f41273211d7b68c68ec45440dd451) -- I'd consider doing a reword to remove upstream issue references.

2024-07-14 12:35 UTC, gregfurman commented on internal/impl/pure/processor_retry.go
> +				Default(0),
Suppose I'm happy with that. Maybe we should include an additional flag in a followup PR to allow disabling though. 

IMHO not 100% sure on the use-case but I thnk it's a harmless addition to make things more flexible.

2024-07-14 12:35 UTC, gregfurman commented on public/service/processor.go
nit: Maybe edit this commit [3b40b7](https://github.com/warpstreamlabs/bento/pull/65/commits/3b40b72e897aeae31f71326f78b67be37106ab7f) message. Your call 🫠

2024-07-14 12:35 UTC, gregfurman commented on website/docs/guides/bloblang/methods.md
> +Available algorithms are: `hmac_sha1`, `hmac_sha256`, `hmac_sha512`, `md5`, `sha1`, `sha256`, `sha512`, `xxhash64`, `crc32`, `fnv32`.
nit: Maybe update the docs in [29567b4f](https://github.com/warpstreamlabs/bento/pull/65/commits/29567b4f41c530def95c30c125bf9de3af16eac5) rather.

2024-07-14 12:37 UTC, gregfurman commented
Looking good, dude! Please update `CHANGELOG.old.md` with relevant changes 😄

2024-07-17 20:02 UTC, jem-davies commented on public/service/processor.go
what would have be changed?

2024-07-18 21:11 UTC, jem-davies commented on website/docs/guides/bloblang/methods.md
> +Available algorithms are: `hmac_sha1`, `hmac_sha256`, `hmac_sha512`, `md5`, `sha1`, `sha256`, `sha512`, `xxhash64`, `crc32`, `fnv32`.
i squashed the update docs commits I made now 😄

2024-07-18 21:16 UTC, jem-davies commented on internal/bloblang/query/methods_test.go
the changes were made on ther merge commit - I did check, but just squashed them together now.

2024-07-18 21:19 UTC, gregfurman commented on website/docs/guides/bloblang/methods.md
> +Available algorithms are: `hmac_sha1`, `hmac_sha256`, `hmac_sha512`, `md5`, `sha1`, `sha256`, `sha512`, `xxhash64`, `crc32`, `fnv32`.
OK awesome. Just gave a quick look and all is seemingly good! Will give another proper look tomorrow morning.

2024-07-19 10:12 UTC, gregfurman commented on CHANGELOG.md
> +- New local testing guide for `bento-lambda`.
Think this should be removed
```suggestion
```

2024-07-19 10:22 UTC, jem-davies commented on CHANGELOG.md
> +- New local testing guide for `bento-lambda`.
edit last commit - `update changelogs`

2024-07-19 11:15 UTC, gregfurman approved these changes
LGTM 💯  Nice job, dude. Some exciting incoming changes!

2024-07-19 11:40 UTC, merged