couchbase: add CAS support
warpstreamlabs/bento pull request #86
Opened 2024-08-01 16:10 UTC by sapk

Set and use [Couchbase CAS](https://docs.couchbase.com/java-sdk/current/howtos/concurrent-document-mutations.html) in metadata `couchbase_cas` to prevent write conflict. 
If an entry is modified by an other process between read and write it will return an error if CAS is mismatched.

This change should be transparent and prevent data loss by default. 
This check can be disabled by clearing the CAS value if needed.

2024-08-03 12:02 UTC, gregfurman requested changes
Thanks for this great contribution @sapk! I've left a couple of comments and suggestions. Mostly some minor grammar and spelling fixes. Also, feel free to discard any `nit` comments.

I'm curious whether we should be allowing for these CAS checks to be toggled via the config instead of making a user clear out metadata fields with bloblang. Not super familiar with Couchbase though so maybe it's more desirable to attach these values by default (like what your PR is currently doing). Let me know your thoughts on this.

2024-08-03 12:10 UTC, sapk commented on internal/impl/couchbase/processor_test.go
> +func TestIntegrationCouchbaseStreamError(t *testing.T) {
Yes one of them should failed because the value it mutate changed in between. The main logic would be to retry by re-reading to get the new value and redo the workflow to not loss the data written by another process.by overwriting it.

2024-08-03 12:14 UTC, sapk commented on internal/impl/couchbase/processor_test.go
> +	assert.Error(t, outBatches[0][0].GetError())
Good idea. it could make it more explicit.

2024-08-03 12:30 UTC, sapk commented on internal/impl/couchbase/processor.go
> +		var cas gocb.Cas // retrieve cas if set
I hesitated also. My current reasoning is that it should be the default logic which provide data loss safety. It can be disabled easily like described in the documentation and furthermore for user that use upsert any old cas value is enough to overwrite the entry. Only replace or remove need the exact last CAS value so it should not impact previous comparison and be safer (furthermore what people using would be expecting). I should have implemented it directly in the initial PR when adding couchbase to benthos. Maybe it would need a notice in release note.

But if we want to be extra safe we can easily make it configurable and disabled by default and next enable it by default and even later remove the configuration. Similar to what go is doing for breaking feature. As you like.

2024-08-03 13:53 UTC, gregfurman commented on internal/impl/couchbase/processor.go
> +		var cas gocb.Cas // retrieve cas if set
This makes sense to me. Based on what you're saying as well as the Couchbase docs, I think this functionality will make the behaviour of the processor "more correct".

However, I think that if a user is experiencing CAS issues as a result of this update, we should make it easier to disable than adding an extra bloblang mapping.

> But if we want to be extra safe we can easily make it configurable and disabled by default and next enable it by default and even later remove the configuration. Similar to what go is doing for breaking feature.

Yeah I'd be happy with this approach. I'd even consider enabling by default. So long as it's easily configurable for users that want to opt out if they experience issues. We could then remove it in the next release.

Will ask @jem-davies to weigh in.

2024-08-03 14:14 UTC, gregfurman commented on internal/impl/couchbase/processor.go
> +		var cas gocb.Cas // retrieve cas if set
OK chatted to Jem. Let's go with the approach you mentioned.

 > But if we want to be extra safe we can easily make it configurable and disabled by default and next enable it by default and even later remove the configuration.

So let's first make it configurable, and disabled by default. In the next release we can enable it, following that we can remove it entirely and always do CAS checks.

You happy with this?

2024-08-07 14:55 UTC, gregfurman commented on internal/impl/couchbase/processor.go
> +		var cas gocb.Cas // retrieve cas if set
@sapk You happy to make this change or should I add it? Lemme know 🙂

2024-08-07 15:03 UTC, sapk commented on internal/impl/couchbase/processor.go
> +		var cas gocb.Cas // retrieve cas if set
I plan to do it. I just didn't have time to focus on it. Sorry.
I should be able to take care of it soon.

2024-08-07 15:21 UTC, gregfurman commented on internal/impl/couchbase/processor.go
> +		var cas gocb.Cas // retrieve cas if set
No worries at all! We're very appreciative of the help 👍

2024-08-08 14:43 UTC, sapk commented on internal/impl/couchbase/processor_test.go
> +	assert.Error(t, outBatches[0][0].GetError())
It is unfortunately not possible because I used the workflow component to run in parallel the writes and the final error is a generic one: `workflow branches failed: [remove]`

2024-08-09 18:03 UTC, sapk commented
It should be good now.

2024-08-11 16:01 UTC, gregfurman commented on internal/impl/couchbase/processor.go
> +		Description("When inserting, replacing or upserting documents, each must have the `content` property set.\n\n### Concurrent Document Mutations\nTo prevent read/write conflicts, Couchbase returns a
```suggestion
		Description("When inserting, replacing or upserting documents, each must have the `content` property set.\n\n### Concurrent Document Mutations\nTo prevent read/write conflicts, Couchbase returns a [_Compare And Swap_ (CAS)](https://docs.couchbase.com/go-sdk/current/howtos/concurrent-document-mutations.html) value with each accessed document. Bento stores these as key/value pairs in metadata with the `couchbase_cas` field. Note: CAS checks are disabled by default. You can configure this by changing the value of `cas_enabled: true`. Future versions will see this enabled by default.").
```

2024-08-11 16:03 UTC, gregfurman commented
@sapk  Thanks for the follow-up! I added one small suggestion for the docs to no longer include that `deleted()` approach of disabling things. If you're happy with that, just regen the docs and we can merge this in.

2024-08-12 19:51 UTC, gregfurman approved these changes
LGTM! 👍

2024-08-12 20:00 UTC, merged